// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jGgt4woGKRj8RGTGGgQBJAPIFUasJtE',
    appId: '1:416825001299:web:701839745fb1b2b9c14da6',
    messagingSenderId: '416825001299',
    projectId: 'boucherie-386db',
    authDomain: 'boucherie-386db.firebaseapp.com',
    storageBucket: 'boucherie-386db.appspot.com',
    measurementId: 'G-7RP9RHY3MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVT5-T-D8wVwNilefQY_zLpOLng9ZLJc',
    appId: '1:416825001299:android:d398d9d5d6713e09c14da6',
    messagingSenderId: '416825001299',
    projectId: 'boucherie-386db',
    storageBucket: 'boucherie-386db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7mE7sHorkj3oDlzJ2oF7Mx0yThNevcRI',
    appId: '1:416825001299:ios:8ebdb0e726bdfe8cc14da6',
    messagingSenderId: '416825001299',
    projectId: 'boucherie-386db',
    storageBucket: 'boucherie-386db.appspot.com',
    iosBundleId: 'com.example.boucherie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7mE7sHorkj3oDlzJ2oF7Mx0yThNevcRI',
    appId: '1:416825001299:ios:8ebdb0e726bdfe8cc14da6',
    messagingSenderId: '416825001299',
    projectId: 'boucherie-386db',
    storageBucket: 'boucherie-386db.appspot.com',
    iosBundleId: 'com.example.boucherie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jGgt4woGKRj8RGTGGgQBJAPIFUasJtE',
    appId: '1:416825001299:web:d1fbe70c21c54485c14da6',
    messagingSenderId: '416825001299',
    projectId: 'boucherie-386db',
    authDomain: 'boucherie-386db.firebaseapp.com',
    storageBucket: 'boucherie-386db.appspot.com',
    measurementId: 'G-287DELM04L',
  );

}